var messages = [
    "Viesti 1",
    "Viesti 2",
    "Viesti 3",
    "Viesti 4",
    "Viesti 5",
    "Viesti 6",
    "Viesti 7",
    "Viesti 8",
    "Viesti 9",
    "Viesti 10",
    "Viesti 11",
    "Viesti 12",
    "Viesti 13",
    "Viesti 14",
    "Viesti 15",    
    "Viesti 16",
    "Viesti 17",
    "Viesti 18",
    "Viesti 19",
    "Viesti 20",
    "Viesti 21",
    "Viesti 22",
    "Viesti 23",
    "Viesti 24"
];
