var messages = [
    "Pidä huolta terveydestäsi. Kuuntele kehosi antamia pieniä signaaleja ja tarvittaessa hiljennä tahtia.",
    "Olet mitä syöt. Syömämme ruoka vaikuttaa sekä fyysiseen että hengelliseen olotilaamme.",
    "Kunnioita itseäsi. Itsekunnioitus on hyvän itsetunnon ehdoton edellytys.",
    "Voit valita miten reagoit. Sen sijaan, että asettaudut puolustusasemiin, pidä itsesi avoimena ja kuuntele toista.",
    "Kuuntele intuitiotasi. Intuitio on sisimpäsi ääni, joka kertoo tiedostamattomat tarpeesi.",
    "Kirjoita muistiin unesi. Unet voivat antaa sinulle oivalluksia ja opastusta.",
    "Lepo on ihanaa. Lepo on aktiivisuuden edellytys. Yritä pitää taukoja joka päivä palautuaksesi rasituksesta.",
    "Yksinkertaista elämääsi. Puhdista arkesi kaikesta siitä, mitä et tarvitse ja mikä ei tuo sinulle mitään.",
    "Rajat luovat läheisyyttä. Mitä selvemmät rajat sinulla on, sitä lähemmäs rajojasi voit päästää muut.",
    "Aikasi on arvokasta. Kun sinulla on tehtäviä, tee ne yksi kerrallaan ja varaa niille häiriötöntä aikaa.",
    "Anna muutokselle aikaa. Suuret muutokset tapahtuvat askel askeleelta ja kullekkin omalla tavallaan.",
    "Hyväksy itsesi sellaisena kuin olet. Yritä olla ymmärtäväinen myös niitä ominaisuuksiasi kohtaa, joista et ole ylpeä.",
    "Luo positiivisia suhteita. Ystävien ja perheen muodostama verkosto on tavattoman tärkeä terveyden ja elämän kannalta.",
    "Löydä paikkasi. Syy huonoon vointiin voi olla se, että oikea ihminen on väärässä paikassa.",
    "Kasvu tapahtuu haasteiden kautta. Elämäsi koostuu haasteista. Ja ne osiin, hae tukea, löydä sinulle toimivat työskentelytavat ja älä luovuta.",
    "Tiedosta ravinnon merkitys. Hyvä terveys alkaa lautaselta. Kysy itseltäsi tekeekö lautasellasi oleva ruoka sinulle hyvää vai pahaa.",
    "Irroita otteesi menneestä. Jättämällä menneisyyden taaksesi tulet vapaammaksi ja voit avata itsesi jollekin uudelle.",
    "On sallittua tuntea itsensä heikoksi. ",
    "Huomioi erilaiset näkökannat. Jokainen tarkastelee maailmaa omalla tavallaan. Ole nöyrä ja avoin muiden tavoille nähdä maailma.",
    "Muutos alkaa sinusta itsestäsi. Mikään ei ole turhempaa kuin koettaa muuttaa toista ihmistä. Voit muuttaa ainoastaan itseäsi. ",
    "Ota askel kohti oikeaa suuntaa. Kuljet kohti päämäärääsi askel kerrallaan. Kulje joka päivä yksi askel suuntaan, jonka koet sinulle oikeaksi.",
    "Unohda uhrirooli. Antaessasi muiden tehdä elämääsi koskevat päätökset olet valinnut uhrin roolin. Kun uskot kykeneväsi ohjaamaan elämääsi, sinä teet päätökset.",
    "Anna itsellesi tarvitsemasi vapaus. Vain sinä tiedät mitä sinä tarvitset. Kiipeä muiden asettamien raamien ulkopuolelle ja löydät vapauden kasvaa ihmisenä.",
    "Leiki enemmän. Leikki lisää luovuutta, iloa ja kontakteja ihmisten välillä. Arkesi sisältää enemmän leikillisiä tilanteita kuin luuletkaan."
];
